apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rvtz82onx-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rvtz82onx-python 
  name: rvtz82onx-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rvtz82onx-python 
