apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rvtz82onx-python 
  janus-idp.io/tekton: rvtz82onx-python
  backstage.io/kubernetes-id: rvtz82onx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rvtz82onx-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml